"""empty message

Revision ID: fbc284727948
Revises: b38e0a098374
Create Date: 2020-05-17 04:18:02.813423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc284727948'
down_revision = 'b38e0a098374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Shows_venue_id_fkey', 'Shows', type_='foreignkey')
    op.drop_constraint('Shows_artist_id_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Artist', ['artist_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'Shows', 'Venue', ['venue_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_artist_id_fkey', 'Shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key('Shows_venue_id_fkey', 'Shows', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
